#!/usr/bin/env bash
#
# lib/mixer.sh — hardware playback-mixer pinning for the dual-session product.
# Sourced by setup.sh / uninstall.sh; depends on lib/common.sh.
#
# Why this exists: forcing the card onto a shared ALSA dmix requires
# `api.alsa.use-acp = false`. ACP is also the layer that maps the desktop
# volume onto the card's hardware mixer, so with ACP off PipeWire applies only
# *software* volume and leaves the card's hardware playback controls (e.g.
# `Master`) at whatever ALSA restored. If that value sits below unity the card
# stays quiet no matter what the desktop slider shows, and a manual fix does
# not survive a reboot because `alsa-restore` re-applies the saved low value.
#
# To keep the shared setup loud, this module pins the detected card's hardware
# playback mixer to unity once at install and re-asserts it on every login via
# a systemd --user oneshot (no root required).
set -euo pipefail

# mixer_systemctl <args...> — best-effort `systemctl --user`; warns, never dies.
mixer_systemctl() {
  if ! systemctl --user "$@" 2>/dev/null; then
    log_warn "systemctl --user $* falló; reinicie la sesión"
  fi
  return 0
}

# Write the standalone, self-contained pinning script. The detected card id and
# the control list are baked in so it can run without the product tree.
mixer_write_script() {
  apply_or_report "Crear directorio $(dirname "$PIN_SCRIPT")" mkdir -p "$(dirname "$PIN_SCRIPT")"
  write_tracked "$PIN_SCRIPT" <<EOF
#!/usr/bin/env bash
#
# Generated by dual-session-setup — do not edit by hand; re-run setup.sh.
# Pins the shared card's hardware playback mixer to unity so the shared-dmix
# path (which disables ACP) stays loud. Safe to run repeatedly.
set -u
CARD="${CARD_ALSA_NAME}"
CARD_FALLBACK="${CARD_INDEX}"
CONTROLS="${MIXER_CONTROLS}"

# Prefer the ALSA card id; fall back to the numeric index when unavailable.
amixer -c "\$CARD" sget Master >/dev/null 2>&1 || CARD="\$CARD_FALLBACK"

# Wait briefly for the card to be ready (login-time race).
for _ in 1 2 3 4 5; do
  amixer -c "\$CARD" sget Master >/dev/null 2>&1 && break
  sleep 1
done

for ctl in \$CONTROLS; do
  amixer -c "\$CARD" sget "\$ctl" >/dev/null 2>&1 || continue
  amixer -c "\$CARD" sset "\$ctl" 100% unmute >/dev/null 2>&1 \\
    || amixer -c "\$CARD" sset "\$ctl" 100% >/dev/null 2>&1 || true
done
exit 0
EOF
  apply_or_report "chmod 700 de $PIN_SCRIPT" chmod 700 "$PIN_SCRIPT"
}

# Write the systemd --user oneshot unit that runs the pin script on login.
mixer_write_unit() {
  local rel="${PIN_SCRIPT#"$HOME"/}"
  apply_or_report "Crear directorio $(dirname "$MIXER_UNIT")" mkdir -p "$(dirname "$MIXER_UNIT")"
  write_tracked "$MIXER_UNIT" <<EOF
[Unit]
Description=Dual-Session audio: pin the shared card's hardware mixer to unity
After=pipewire.service wireplumber.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=%h/${rel}

[Install]
WantedBy=default.target
EOF
}

# Install + enable the pin (and apply it immediately so no relogin is needed).
mixer_install() {
  log_info "--- Mixer de hardware (evita el volumen bajo tras reiniciar) ---"
  mixer_write_script
  mixer_write_unit
  apply_or_report "systemctl --user daemon-reload" mixer_systemctl daemon-reload
  apply_or_report "Habilitar servicio ${MIXER_SERVICE}" mixer_systemctl enable --now "${MIXER_SERVICE}"
  apply_or_report "Actualizar manifiesto $MANIFEST" update_manifest
  if [ "$CHECK" -eq 0 ] && [ "$DRY_RUN" -eq 0 ]; then
    log_info "Fijando el mixer de hardware ahora..."
    if ! bash "$PIN_SCRIPT"; then
      log_warn "No se pudo fijar el mixer ahora; se hará al iniciar sesión"
    fi
  fi
}

# Remove the pin: disable the unit, drop the unit + script (only while their
# content still matches the manifest), then reload systemd.
mixer_remove() {
  local path="" sig="" actual=""

  log_info "--- Quitar pin del mixer de hardware ---"
  apply_or_report "Deshabilitar servicio ${MIXER_SERVICE}" mixer_systemctl disable --now "${MIXER_SERVICE}"

  for path in "$MIXER_UNIT" "$PIN_SCRIPT"; do
    sig="$(manifest_sig "$path")"
    [ -n "$sig" ] || continue
    [ -f "$path" ] || continue
    actual="$(md5sum < "$path" | awk '{print $1}')"
    if [ "$sig" = "$actual" ]; then
      apply_or_report "Eliminar $path" rm -f "$path"
    else
      log_warn "Se conserva $path (modificado tras la instalación)"
    fi
  done

  apply_or_report "systemctl --user daemon-reload" mixer_systemctl daemon-reload
}
